### ISSUE TITLE
IE sim crashes when going in to or out of full screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#451] opened 2019-09-17 15:17 UTC
Device
Bates and Dell
OS
Win 7 and 10
Browser
IE
Problem Description
For https://github.com/phetsims/QA/issues/426.  Occurs in published version.
When entering or exiting full screen on certain screens, the sim will crash and reload.  I couldn't seem to get the console to stay up to log an error.  On Win 7 it seems to be the first and third screen, and on Win 10 it seems to be the first, second, and third screens.  The home screen and diffusion screen both seem ok.

**Comment by KatieWoe** [comment] 2019-09-17 15:34
Did a quick check on Win 10 for Wave Intro and it seems to happen there on the water screen but not on sound or light.

**Comment by KatieWoe** [comment] 2019-09-17 15:39
One last edit.  Win 7 does crash on the second screen.  It only crashes if water is the scene up.  If you switch to sound or light it doesn't.  My guess is that is how its slipped through until now.

**Comment by ariel-phet** [comment] 2019-09-19 02:22
@KatieWoe does this occur on the published version?

**Comment by ariel-phet** [comment] 2019-09-19 02:22
@samreid if this is a problem on the published version, this issue can be deferred.

**Comment by arouinfar** [comment] 2019-09-19 02:56
@ariel-phet it does happen on the published version. In latest and rc.3, launching full screen from screens 1-3 will crash the sim. The window will automatically re-load itself, but after the sim crashes a few times, IE gets fed up and issues this warning. To reload the sim, I need to first delete the junk that IE inserted at the front of the URL.
![image](https://user-images.githubusercontent.com/8419308/65209601-ed4f8e00-da55-11e9-83fd-421a9b79c306.png)

Interestingly, if I launch full screen from the home screen, the sim behaves fine. I can interact with all of the screens and the sim doesn't crash. 

<details>
<summary><b>Troubleshooting Info</b></summary>

Name:  Wave Interference 
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-rc.3/phet/wave-interference_en_phet.html
Version: 2.0.0-rc.3 2019-09-13 03:56:27 UTC
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko
Language: en-US
Window: 2560x1327
Pixel Ratio: 1.5/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
</details>

**Comment by KatieWoe** [comment] 2019-09-19 14:38
>Occurs in published version.

>It only crashes if water is the scene up

**Comment by samreid** [comment] 2019-09-19 14:59
I can reproduce this problem on my bootcamp IE, and found that the problem is triggered even when manually adjusting the window size (not just using the full screen button).

**Comment by samreid** [comment] 2019-09-19 15:00
> @samreid if this is a problem on the published version, this issue can be deferred.

@ariel-phet OK, we'll move forward with publication without work on this issue.  How would you like to prioritize/schedule work on this issue after publication?

**Comment by ariel-phet** [comment] 2019-09-19 16:18
@samreid after publication, let plan to have a meeting to go through the deferred issues, we can prioritize then.

**Comment by samreid** [comment] 2020-06-01 16:50
@ariel-phet or @arouinfar should we work on this issue for the upcoming Waves Intro sonification/keyboard navigation release?

**Comment by arouinfar** [comment] 2020-06-01 16:58
My guess is no, but it would be good for @ariel-phet to confirm.

**Comment by ariel-phet** [comment] 2020-06-01 20:51
@samreid we will not work on this issue. Marking as `wontfix`

**Closed** 2020-06-01 20:52 UTC
Labels: type:bug, type:wontfix
