### ISSUE TITLE
Peak on water "graph" skewed to front of shaded wave. 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/wave-interference#143] opened 2018-09-14 05:07 UTC
In playing, I noticed that the water graph of the height at the center point of the pool is perhaps a bit off in phase? The peak looks to be at the front portion of the displayed blue shaded region instead of basically in the center of the shaded region. If it was in the back portion that could be reasoned because the energy of the wave is spreading out, but I can't come up with a reason for it to be skewed to the leading edge of the wave. 
![image](https://user-images.githubusercontent.com/5096804/45530827-c955ce80-b7a9-11e8-9d81-03ff41e2f825.png)

**Comment by arouinfar** [comment] 2018-09-17 20:39
@kathy-phet it does indeed look a bit off.

@samreid it looks like the peak of waves in the graph do not correspond to the center of the crest at the centerline. Can you take a look?
<img width="567" alt="screen shot 2018-09-17 at 2 37 25 pm" src="https://user-images.githubusercontent.com/8419308/45648981-3fe31c80-ba87-11e8-9fe4-e4c022407158.png">

**Comment by samreid** [comment] 2018-09-19 03:35
I tested the same spike that was used here https://github.com/phetsims/wave-interference/issues/133#issuecomment-422466033 and referred to here https://github.com/phetsims/wave-interference/issues/142#issuecomment-422603485 and saw that the lattice matches up pretty well with the wave area chart (transparency added to make it easier to visualize):

![image](https://user-images.githubusercontent.com/679486/45729592-5b831b80-bb8a-11e8-9085-e54efb366b67.png)

**Comment by samreid** [comment] 2018-09-19 23:49
I'm not sure of the best way to investigate this.  Tagging for design meeting to get ideas.

**Comment by arouinfar** [comment] 2018-09-21 20:46
In design meeting yesterday, we noticed that the source point on the lattice also seems misaligned with the graph. 

Here's another example taken from dev.32:
![image](https://user-images.githubusercontent.com/8419308/45904172-7da6b480-bda9-11e8-9c8d-f0b2cbf88d5b.png)

**Comment by samreid** [comment] 2018-10-04 03:43
I reduced the lattice size to a width of 10 and padding of 0 and saw this correspondence between the wave area and the chart:

![image](https://user-images.githubusercontent.com/679486/46451754-58c12280-c755-11e8-9260-4905e69c2cbb.png)

**Comment by samreid** [comment] 2018-10-04 03:50
I'm seeing the same offset for plane waves:

![image](https://user-images.githubusercontent.com/679486/46451947-5d3a0b00-c756-11e8-9f5d-7446ec10c237.png)

**Comment by samreid** [comment] 2018-10-05 14:52
I went to the rasterized canvasnode as mentioned in the preceding comment and created a debug slice on the lattice like so:

```
Index: js/common/model/Lattice.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/Lattice.js	(revision f1aa2e6c7822df81d145ee9c5fde3ad45d6516cf)
+++ js/common/model/Lattice.js	(date 1538750967000)
@@ -270,6 +270,14 @@
       return ( 1 - depthInDampRegion * 0.0001 );
     }
 
+    debug() {
+      this.clear();
+      var d = 8;
+      for ( var i = 0; i < this.height; i++ ) {
+        this.setCurrentValue( d, i, 10 );
+      }
+    }
+
     /**
      * Resets all of the wave values to 0
      * @public
Index: js/common/view/LatticeCanvasNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/LatticeCanvasNode.js	(revision f1aa2e6c7822df81d145ee9c5fde3ad45d6516cf)
+++ js/common/view/LatticeCanvasNode.js	(date 1538750701000)
@@ -1,135 +1,110 @@
-// Copyright 2017-2018, University of Colorado Boulder
+// Copyright 2017, University of Colorado Boulder
 
 /**
  * Renders the main area of the lattice (doesn't include the damping regions) using 2d canvas.
  *
  * @author Sam Reid (PhET Interactive Simulations)
  */
-define( require => {
+define( function( require ) {
   'use strict';
 
   // modules
-  const CanvasNode = require( 'SCENERY/nodes/CanvasNode' );
-  const Color = require( 'SCENERY/util/Color' );
-  const Util = require( 'DOT/Util' );
-  const Vector2 = require( 'DOT/Vector2' );
-  const waveInterference = require( 'WAVE_INTERFERENCE/waveInterference' );
-  const WaveInterferenceConstants = require( 'WAVE_INTERFERENCE/common/WaveInterferenceConstants' );
-  const WaveInterferenceUtils = require( 'WAVE_INTERFERENCE/common/WaveInterferenceUtils' );
+  var Bounds2 = require( 'DOT/Bounds2' );
+  var CanvasNode = require( 'SCENERY/nodes/CanvasNode' );
+  var Color = require( 'SCENERY/util/Color' );
+  var inherit = require( 'PHET_CORE/inherit' );
+  var Util = require( 'DOT/Util' );
+  var Vector2 = require( 'DOT/Vector2' );
+  var waveInterference = require( 'WAVE_INTERFERENCE/waveInterference' );
 
   // constants
-  const CELL_WIDTH = WaveInterferenceConstants.CELL_WIDTH;
-
-  class LatticeCanvasNode extends CanvasNode {
+  var CELL_WIDTH = 10; // TODO: this number no longer seems to matter
 
-    /**
-     * @param {Lattice} lattice
-     * @param {Object} [options]
-     */
-    constructor( lattice, options ) {
-
-      options = _.extend( {
-
-        // only use the visible part for the bounds (not the damping regions)
-        canvasBounds: WaveInterferenceUtils.getCanvasBounds( lattice ),
-        layerSplit: true // ensure we're on our own layer
-      }, options );
-
-      super( options );
+  /**
+   * @param {Lattice} lattice
+   * @param {Object} [options]
+   * @constructor
+   */
+  function LatticeCanvasNode( lattice, options ) {
 
-      // @private
-      this.lattice = lattice;
+    // @private
+    this.lattice = lattice;
 
-      // @private
-      this.baseColor = new Color( 'blue' );
+    // @private
+    this.baseColor = new Color( 'blue' );
 
-      // @public {Color|null} - settable, if defined shows unvisited lattice cells as specified color, used for light source
-      this.vacuumColor = null;
+    // @public {Color|null} - settable, if defined shows unvisited lattice cells as specified color, used for light source
+    this.vacuumColor = null;
 
-      // Render into a sub-canvas which will be drawn into the rendering context at the right scale.
-      const w = this.lattice.width - this.lattice.dampX * 2;
-      const h = this.lattice.height - this.lattice.dampY * 2;
-      this.directCanvas = document.createElement( 'canvas' );
-      this.directCanvas.width = w;
-      this.directCanvas.height = h;
-      this.directContext = this.directCanvas.getContext( '2d' );
-      this.imageData = this.directContext.createImageData( w, h );
+    // only use the visible part for the bounds (not the damping regions)
+    options = _.extend( { canvasBounds: new Bounds2( 0, 0, ( lattice.width - lattice.dampX * 2 ) * CELL_WIDTH, ( lattice.height - lattice.dampY * 2 ) * CELL_WIDTH ) }, options );
+    CanvasNode.call( this, options );
+
+    var self = this;
 
-      // Invalidate paint when model indicates changes
-      const invalidateSelfListener = this.invalidatePaint.bind( this );
-      lattice.changedEmitter.addListener( invalidateSelfListener );
-    }
+    lattice.changedEmitter.addListener( function() {
+      self.invalidatePaint();
+    } );
+  }
 
+  waveInterference.register( 'LatticeCanvasNode', LatticeCanvasNode );
+
+  return inherit( CanvasNode, LatticeCanvasNode, {
 
     /**
      * Convert the given point (in the local coordinate frame) to the corresponding i,j (integral) coordinates on the lattice.
      * @param {Vector2} point - point in the local coordinate frame
      * @returns {Vector2}
      */
-    localPointToLatticePoint( point ) {
+    localPointToLatticePoint: function( point ) {
       return new Vector2( Math.floor( point.x / CELL_WIDTH ), Math.floor( point.y / CELL_WIDTH ) );
-    }
+    },
 
     /**
      * Sets the color of the peaks of the wave.
      * @param {Color} color
      * @public
      */
-    setBaseColor( color ) {
+    setBaseColor: function( color ) {
       this.baseColor = color;
       this.invalidatePaint();
-    }
+    },
 
     /**
-     * Draws into the canvas.
+     * Draws into the canvas
      * @param {CanvasRenderingContext2D} context
      */
-    paintCanvas( context ) {
-
-      let m = 0;
-      const data = this.imageData.data;
-      const dampX = this.lattice.dampX;
-      const dampY = this.lattice.dampY;
-      const width = this.lattice.width;
-      const height = this.lattice.height;
-      let intensity;
-      for ( let i = dampX; i < width - dampX; i++ ) {
-        for ( let k = dampY; k < height - dampY; k++ ) {
-
-          const waveValue = this.lattice.getInterpolatedValue( k, i );  // Note this is transposed because of the ordering of putImageData
-
-          const MIN_SHADE = 0.03; // Stop before 0 because 0 is too jarring
-          intensity = Util.linear( -1.5, 2, MIN_SHADE, 1, waveValue );
-          intensity = Util.clamp( intensity, MIN_SHADE, 1 );
+    paintCanvas: function( context ) {
 
-          // Note this interpolation doesn't include the gamma factor that Color.blend does
-          let r = this.baseColor.red * intensity;
-          let g = this.baseColor.green * intensity;
-          let b = this.baseColor.blue * intensity;
+      for ( var i = this.lattice.dampX; i < this.lattice.width - this.lattice.dampX; i++ ) {
+        for ( var k = this.lattice.dampY; k < this.lattice.height - this.lattice.dampY; k++ ) {
 
-          if ( this.vacuumColor && !this.lattice.hasCellBeenVisited( k, i ) ) { // Note this is transposed because of the ordering of putImageData
-            r = this.vacuumColor.r;
-            g = this.vacuumColor.g;
-            b = this.vacuumColor.b;
+          // Color mapping:
+          // wave value => color value
+          //          1 => 1.0
+          //          0 => 0.3
+          //         -1 => 0.0
+          var value = this.lattice.getCurrentValue( i, k );
+          var intensity;
+          var CUTOFF = 0.3;
+          if ( value > 0 ) {
+            intensity = Util.linear( 0, 2, CUTOFF, 1, value );
+            intensity = Util.clamp( intensity, CUTOFF, 1 );
+          }
+          else {
+            var MIN_SHADE = 0.03; // Stop before 0 because 0 is too jarring
+            intensity = Util.linear( -1.5, 0, MIN_SHADE, CUTOFF, value );
+            intensity = Util.clamp( intensity, MIN_SHADE, CUTOFF );
           }
 
-          const offset = 4 * m;
-          data[ offset + 0 ] = r;
-          data[ offset + 1 ] = g;
-          data[ offset + 2 ] = b;
-          data[ offset + 3 ] = 255; // Fully opaque
-          m++;
-        }
-      }
-      this.directContext.putImageData( this.imageData, 0, 0 );
-
-      // draw the sub-canvas to the rendering context at the appropriate scale
-      context.save();
-      context.transform( CELL_WIDTH, 0, 0, CELL_WIDTH, 0, 0 );
-      context.drawImage( this.directCanvas, 0, 0 );
-      context.restore();
-    }
-  }
-
-  return waveInterference.register( 'LatticeCanvasNode', LatticeCanvasNode );
+          var color = this.baseColor.blend( Color.black, 1 - intensity ); // TODO: Performance caveat
+          if ( this.vacuumColor && !this.lattice.hasCellBeenVisited( i, k ) ) {
+            color = this.vacuumColor;
+          }
+          context.fillStyle = color.toCSS();
+          context.fillRect( ( i - this.lattice.dampX ) * CELL_WIDTH, ( k - this.lattice.dampY ) * CELL_WIDTH, CELL_WIDTH + 1, CELL_WIDTH + 1 ); // +1 is to eliminate seams // TODO: x-offset?
+        }
+      }
+    }
+  } );
 } );
\ No newline at end of file
Index: js/common/WaveInterferenceConstants.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/WaveInterferenceConstants.js	(revision f1aa2e6c7822df81d145ee9c5fde3ad45d6516cf)
+++ js/common/WaveInterferenceConstants.js	(date 1538750788000)
@@ -53,12 +53,12 @@
 
     // Cell that oscillates, specified as an offset from the origin of the lattice (includes damping region).  This value
     // must be coordinated with WaterEmitterNode's waterDrops[ index ].centerX
-    POINT_SOURCE_HORIZONTAL_COORDINATE: 23,
+    POINT_SOURCE_HORIZONTAL_COORDINATE: 2,
 
-    LATTICE_DIMENSION: 100,
+    LATTICE_DIMENSION: 11,
 
     // Number of cells around the boundary of the lattice to avoid reflections at the edge
-    LATTICE_PADDING: 20,
+    LATTICE_PADDING: 0,
 
     // Parameters for sound.  These are constants in the simulation, but wrapped in Properties for fine
     // tuning with developer controls.
Index: js/waves/model/WavesScreenModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/waves/model/WavesScreenModel.js	(revision f1aa2e6c7822df81d145ee9c5fde3ad45d6516cf)
+++ js/waves/model/WavesScreenModel.js	(date 1538750701000)
@@ -219,7 +219,7 @@
       } );
 
       // @public {BooleanProperty} - whether the model is moving forward in time
-      this.isRunningProperty = new BooleanProperty( true );
+      this.isRunningProperty = new BooleanProperty( false );
 
       // @public {BooleanProperty} - whether the measuring tape has been dragged out of the toolbox into the play area
       this.isMeasuringTapeInPlayAreaProperty = new BooleanProperty( false );
@@ -406,44 +406,46 @@
      */
     advanceTime( wallDT, manualStep ) {
 
-      const frequency = this.sceneProperty.get().frequencyProperty.get();
-      const period = 1 / frequency;
-
-      // Animate the rotation, if it needs to rotate.  This is not subject to being paused, because we would like
-      // students to be able to see the side view, pause it, then switch to the corresponding top view, and vice versa.
-      const sign = this.viewTypeProperty.get() === ViewType.TOP ? -1 : +1;
-      this.rotationAmountProperty.value = Util.clamp( this.rotationAmountProperty.value + wallDT * sign * 1.4, 0, 1 );
+      this.lattice.debug();
 
-      if ( !this.isRunningProperty.get() && !manualStep ) {
-        return;
-      }
-
-      const dt = wallDT * this.sceneProperty.value.timeScaleFactor;
-      this.timeProperty.value += dt;
-
-      // If the pulse is running, end the pulse after one period
-      if ( this.pulseFiringProperty.get() ) {
-        const timeSincePulseStarted = this.timeProperty.value - this.pulseStartTime;
-
-        // For 50% longer than one pulse, keep the oscillator fixed at 0 to prevent "ringing"
-        if ( timeSincePulseStarted > period * 1.5 ) {
-          this.pulseFiringProperty.set( false );
-          this.pulseStartTime = 0;
-        }
-      }
-
-      // Update the lattice
-      this.lattice.step( () => this.setSourceValues() );
-
-      if ( this.isTimerRunningProperty.get() ) {
-        this.timerElapsedTimeProperty.set( this.timerElapsedTimeProperty.get() + dt );
-      }
-
-      this.lattice.interpolationRatio = this.eventTimer.getRatio();
-
-      // Scene-specific physics updates
-      this.sceneProperty.value.step( this, dt );
-
+      // const frequency = this.sceneProperty.get().frequencyProperty.get();
+      // const period = 1 / frequency;
+      //
+      // // Animate the rotation, if it needs to rotate.  This is not subject to being paused, because we would like
+      // // students to be able to see the side view, pause it, then switch to the corresponding top view, and vice versa.
+      // const sign = this.viewTypeProperty.get() === ViewType.TOP ? -1 : +1;
+      // this.rotationAmountProperty.value = Util.clamp( this.rotationAmountProperty.value + wallDT * sign * 1.4, 0, 1 );
+      //
+      // if ( !this.isRunningProperty.get() && !manualStep ) {
+      //   return;
+      // }
+      //
+      // const dt = wallDT * this.sceneProperty.value.timeScaleFactor;
+      // this.timeProperty.value += dt;
+      //
+      // // If the pulse is running, end the pulse after one period
+      // if ( this.pulseFiringProperty.get() ) {
+      //   const timeSincePulseStarted = this.timeProperty.value - this.pulseStartTime;
+      //
+      //   // For 50% longer than one pulse, keep the oscillator fixed at 0 to prevent "ringing"
+      //   if ( timeSincePulseStarted > period * 1.5 ) {
+      //     this.pulseFiringProperty.set( false );
+      //     this.pulseStartTime = 0;
+      //   }
+      // }
+      //
+      // // Update the lattice
+      // this.lattice.step( () => this.setSourceValues() );
+      //
+      // if ( this.isTimerRunningProperty.get() ) {
+      //   this.timerElapsedTimeProperty.set( this.timerElapsedTimeProperty.get() + dt );
+      // }
+      //
+      // this.lattice.interpolationRatio = this.eventTimer.getRatio();
+      //
+      // // Scene-specific physics updates
+      // this.sceneProperty.value.step( this, dt );
+      //
       // Notify listeners that a frame has advanced
       this.stepEmitter.emit();
 

```

And this is centered in the middle:
![image](https://user-images.githubusercontent.com/679486/46542462-b780bc00-c87b-11e8-89b1-9fc5e1d840c0.png)

However, to the left and right sides it is not accurate:

![image](https://user-images.githubusercontent.com/679486/46542511-cf584000-c87b-11e8-8630-7ebc7ab99010.png)

![image](https://user-images.githubusercontent.com/679486/46542547-e860f100-c87b-11e8-9d47-64930862fad7.png)

**Comment by samreid** [comment] 2018-10-05 15:16
Moving the boundaries of the mapping like so gets things to match up:

![image](https://user-images.githubusercontent.com/679486/46543885-45aa7180-c87f-11e8-8ba3-96574f7e8e1a.png)

```js
// getWaterSideShape
const x = Util.linear( -0.5, array.length - 1+0.5, waveAreaBounds.left, waveAreaBounds.right, i ) + dx;
```

**Comment by samreid** [comment] 2018-10-05 15:33
Looks OK for sound at this frequency:
![image](https://user-images.githubusercontent.com/679486/46544693-873c1c00-c881-11e8-8995-c5d7ecd2acff.png)

And at the sound low frequency:
![image](https://user-images.githubusercontent.com/679486/46544742-9de27300-c881-11e8-989b-dbf9ecbb8a53.png)

**Comment by samreid** [comment] 2018-10-05 15:39
@arouinfar I published a version with the improvement listed above.  It seems some cases are better, but can you please help me test more thoroughly?  Does this resolve or reduce the problem?  If the problem is still present, where is it worst and how severe is it?  Also be aware I created https://github.com/phetsims/wave-interference/issues/165 about a problem I noted in water plane wave frequency--not sure if that pertains to this issue or not.

https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.38/phet/wave-interference_en_phet.html

**Comment by arouinfar** [comment] 2018-10-05 21:28
@samreid I tested low, middle, and high frequencies in all scenes, and the correspondence between the lattice and graph is looking really good. I think we can go ahead and close this issue.

**Comment by samreid** [comment] 2019-01-11 00:18
I hardcoded a wave at 75th cell and it matched perfectly in all scenes:

![image](https://user-images.githubusercontent.com/679486/51005315-84456d00-14fb-11e9-82af-b6f4f19bfb3c.png)

I also tried a diagonal in case the vertical coordinate is the problem, but it still looked OK:

![image](https://user-images.githubusercontent.com/679486/51005353-a9d27680-14fb-11e9-8581-2623ccade12a.png)

**Comment by samreid** [comment] 2019-01-11 00:20
Green light looks pretty well matched on my Mac Chrome:

![image](https://user-images.githubusercontent.com/679486/51005413-e900c780-14fb-11e9-9784-bb3d4f12a9c8.png)

![image](https://user-images.githubusercontent.com/679486/51005419-f322c600-14fb-11e9-8e8c-73fe65dc6dff.png)

@arouinfar and @kathy-phet do you see the problem for the default green wavelength of light? Can you please paste a screenshot of what you are seeing?

**Comment by samreid** [comment] 2019-01-11 00:21
I wonder if there is some platform specific GPU issue that is misaligning the cells when blown up from 60x60 to full screen.

**Comment by arouinfar** [comment] 2019-01-11 17:57
@kathy-phet @samreid this is what I'm seeing on my Mac following the instructions in https://github.com/phetsims/wave-interference/issues/143#issuecomment-453365003.

<details><summary>Troubleshooting information</summary>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.60/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.60 2019-01-11 03:24:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1440x790
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

![image](https://user-images.githubusercontent.com/8419308/51050327-9e2f9000-158d-11e9-8491-3245c7cb6124.png)

This is what I'm seeing in dev.59. The alignment is looking pretty good, and any mis-match is likely due to the low number of points used to make the graph.
![image](https://user-images.githubusercontent.com/8419308/51050891-793c1c80-158f-11e9-878c-5fd7841ee71a.png)

**Comment by kathy-phet** [comment] 2019-01-11 19:39
Opening dev.60, mine looks like this - which seems different than Amy's:  
![image](https://user-images.githubusercontent.com/5096804/51055664-c0c9a500-159d-11e9-8e7b-924df3500e77.png)

**Comment by kathy-phet** [comment] 2019-01-11 19:43
The relative positioning of the two representations seems to be effected by resizing the screen. Here is another snapshot at a different size of the screen: 
![image](https://user-images.githubusercontent.com/5096804/51055851-63822380-159e-11e9-8144-cef81ca82113.png)

**Comment by samreid** [comment] 2019-01-11 19:46
Can you resize your screen until it is "as bad as possible", so we can see the most extreme case?

**Comment by kathy-phet** [comment] 2019-01-11 20:31
On dev.59, at my full screen aspect ratio - I see some off set: 
![image](https://user-images.githubusercontent.com/5096804/51057957-7697f200-15a4-11e9-8717-ee875af18989.png)

This is what I see when closer to matching dev bounds aspect ratio. Pretty similar: 
![image](https://user-images.githubusercontent.com/5096804/51058188-35eca880-15a5-11e9-9ea5-12f9a08213f8.png)

**Comment by samreid** [comment] 2019-01-11 20:34
Wasn't it much worse on your computer on Thursday?

**Comment by kathy-phet** [comment] 2019-01-11 20:36
With resizing I just she shifts around, here is what seems to be about as bad as I can get it. Which is similar to my previous version. I'm not sure why they resize relative to each other? Do you under stand that? 
![image](https://user-images.githubusercontent.com/5096804/51058339-b0b5c380-15a5-11e9-956d-8938b0572897.png)

**Comment by kathy-phet** [comment] 2019-01-11 20:37
Overall though, I would say this degree of issue shouldn't block publication, but maybe could be reexamined at WebGL time?

**Comment by kathy-phet** [comment] 2019-01-11 20:38
I think it was worse on Thursday. I cannot explain why.

**Comment by samreid** [comment] 2019-01-16 04:57
I wonder if this problem is impacted (hopefully for the better) by #315.

**Comment by samreid** [comment] 2019-01-23 15:20
@kathy-phet can you please test https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.66/phet/wave-interference_en_phet.html and report if this problem is reduced on your platform now that the lattice resolution has been increased?

**Comment by samreid** [comment] 2019-03-22 21:53
Labeling for design meeting to see if there's anything else to do for this issue.

**Comment by samreid** [comment] 2019-04-11 20:42
@ariel-phet and @kathy-phet will take a look at the published sim (which has the larger lattice) and see if it suffers from problem we discussed in this issue.

**Comment by ariel-phet** [comment] 2019-04-24 23:45
I looked carefully at the published sim on Win 10 on both Chrome and FF. I also tried at some different aspect ratios, everything looked completely fined at lined up to as best as my eye could tell. We also have no reports of this issue from "the world" so I am confident it is safe to close, and @kathy-phet does not need to bother testing.

**Closed by ariel-phet** 2019-04-24 23:45 UTC
Labels: status:ready-for-review
