### ISSUE TITLE
Chromebook fonts too tall? Reload button overlap with slider panel

### ISSUE THREAD

**Issue by rea-laura** [phetsims/wave-interference#326] opened 2019-01-23 17:28 UTC
<b>Test Device</b>

Chadwick

<b>Operating System</b>

Chrome OS 71.0.3578.127

<b>Browser</b>

Chrome 71.0.3578.127

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/264:
Reload button overlaps slightly with slider panel

<b>Steps to Reproduce</b>

1) open sim and go to "Slits" page
2) select the laser pointer
3) note that the bottom of the slits slider panel overlaps slightly with the reload button

<b>Visuals</b>

![screenshot-phet-dev colorado edu-2019 01 23-10-23-33](https://user-images.githubusercontent.com/44005544/51625107-95c64600-1ef9-11e9-8c1d-2b2632c87768.png)

**Comment by arouinfar** [comment] 2019-01-23 17:35
That's odd. This is what I see when using `?dev` on mac OS 10.13.6/latest Chrome.

![image](https://user-images.githubusercontent.com/8419308/51625473-7bd93300-1efa-11e9-94a4-1d28e6f9ffda.png)

**Comment by rea-laura** [comment] 2019-01-23 17:38
Interesting... I found it both in and out of full screen, and when resizing the window. It seems to keep the same amount of overlap no matter what I do to resize the sim.

**Comment by rea-laura** [comment] 2019-01-23 18:09
iOS 10.14.2 latest chrome:
![screen shot 2019-01-23 at 11 06 20 am](https://user-images.githubusercontent.com/44005544/51627411-35d29e00-1eff-11e9-9041-9106d08c9c68.png)
Seems as though it only happened on the chrome book for whatever reason. I'll keep updating if I find it on anything else.

**Comment by arouinfar** [comment] 2019-01-23 20:10
@rea-laura can you load the sim with the ?dev query parameter on Chadwick and take a screenshot of the full screen (or sim window)?

**Comment by samreid** [comment] 2019-01-23 22:33
Maybe Chromebook has slightly taller fonts than other platforms?  @arouinfar operating on that hypothesis, how do you want to proceed?

**Comment by samreid** [comment] 2019-01-23 23:04
I overlayed Mac/Chrome on the given screenshot to see the difference:  Chromebook is the lower one:

![image](https://user-images.githubusercontent.com/679486/51643063-84486280-1f28-11e9-97df-a749d3c1248e.png)

**Comment by arouinfar** [comment] 2019-01-23 23:04
Here's a side-by-side comparison of a Chromebook (Feynman) and MacBook. 

Chromebook (left), MacBook Pro (middle), Overlap (right)
![image](https://user-images.githubusercontent.com/8419308/51642660-367f2a80-1f27-11e9-95c6-b37067376ea9.png)

The font sizes don't actually look different. Here are a few examples of what happens when I perfectly align some of the text in the sim. Somehow, the padding between elements is messed up.


| Perfectly aligned word | Screenshot |
| --- | --- |
| "Amplitude" | ![image](https://user-images.githubusercontent.com/8419308/51642870-e18fe400-1f27-11e9-9cb8-9ca8ea716c51.png) |
| "Graph" | ![image](https://user-images.githubusercontent.com/8419308/51642779-9c6bb200-1f27-11e9-8137-2f3cbc72f8b5.png) |
| "One Slit" | ![image](https://user-images.githubusercontent.com/8419308/51642825-b4dbcc80-1f27-11e9-836a-525ccfa8a030.png) |

I'm at a loss here. Not entirely sure what we can do, other than reduce the padding between items, which will make the UX a bit worse for non-Chromebooks. Any thoughts @ariel-phet @samreid?

**Comment by arouinfar** [comment] 2019-01-23 23:08
Unfortunately, it seems to be a general Chromebook issue, since @rea-laura first reported the issue on Chadwick, and the screenshots in https://github.com/phetsims/wave-interference/issues/326#issuecomment-457001204 are from Feynman.

**Comment by KatieWoe** [comment] 2019-01-23 23:10
@arouinfar don't know if you still need this but:
![pastedimage](https://user-images.githubusercontent.com/41024075/51643365-6af3e600-1f29-11e9-935b-627e6be3ad30.png)

**Comment by samreid** [comment] 2019-01-24 01:17
The overlap doesn't look great, but it doesn't seem pedagogically problematic--button is still visible and usable.  Perhaps leave it alone for this simulation and open a scenery issue about Chromebook font sizing?

**Comment by samreid** [comment] 2019-01-24 01:21
If we decide to investigate, a good first step seems to be to install the Chromebook font (Roboto?) on a development machine, update scenery to use that font by default, and try to reproduce the problem.

**Comment by ariel-phet** [comment] 2019-01-24 03:39
@samreid @arouinfar we are not putting the sim out with that overlap on chromebook

I think we can get the pixels we need with a few minor tweaks. 
1. Shrink the panel vertically one pixel or so towards the Frequency label
2. Move the Separator line below sources and the check boxes underneath up tighter to the sources
3. Done below (original then tweaked) I think would buy enough pixels to remove the overlap 

![wishrink](https://user-images.githubusercontent.com/4051174/51653046-051a5500-1f4f-11e9-915a-112f125905e3.PNG)
![wishrink2](https://user-images.githubusercontent.com/4051174/51653049-08154580-1f4f-11e9-9cd0-271de2721f78.png)

**Comment by samreid** [comment] 2019-01-24 04:08
I tried installing and specifying Roboto, but it didn't seem to work.  This patch simulates the problem pretty well on Mac/Chrome:

```
Index: js/nodes/Text.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/nodes/Text.js	(revision e86c87e629405e3a91c043debb0cf538cc2298db)
+++ js/nodes/Text.js	(date 1548302755000)
@@ -315,6 +315,7 @@
       if ( this.hasStroke() ) {
         selfBounds.dilate( this.getLineWidth() / 2 );
       }
+      selfBounds.dilateY( 1 );
 
       var changed = !selfBounds.equals( this._selfBounds );
       if ( changed ) {
```
That is, each text bounds is dilated by about 2 view units vertically.  I'll use this to apply the changes above.

**Comment by samreid** [comment] 2019-01-24 04:17
With that test harness, I adjusted the variables recommended in https://github.com/phetsims/wave-interference/issues/326#issuecomment-457055532

Specifically, I reduced the control panel y margin from 7 to 4 and the separator top spacing from 12 to 8 and it seems OK in my test harness.

It looks like this with the test harness, which hopefully mimics the Chrome problem well:

![image](https://user-images.githubusercontent.com/679486/51654232-187bef00-1f54-11e9-8f98-98b980dfd7d6.png)

Just a word of warning for the future: someone might propose using `if platform.chromebook, erode text bounds by 1 vertically`, but that is very risky, because Chromebook might fix this one day, then all our Chromebook layouts would be crunched.

@ariel-phet does that look OK to you?  Should I commit + push?

**Comment by ariel-phet** [comment] 2019-01-24 04:20
@samreid that looks acceptable to me feel free to commit and push.

**Comment by pixelzoom** [comment] 2019-01-24 04:37
Re the patch in https://github.com/phetsims/wave-interference/issues/326#issuecomment-457060174...  You'd need to apply the same patch to RichText and any other text Nodes that aren't a subtype of Text.

**Comment by KatieWoe** [comment] 2019-01-24 16:08
@pixelzoom @samreid this issue seems resolved on Chadwick

**Comment by samreid** [comment] 2019-01-24 16:10
Thanks, I'll close this sim-specific issue and open a scenery issue for potential follow-up.

**Closed by samreid** 2019-01-24 16:10 UTC
Labels: status:ready-for-review, type:bug
