### ISSUE TITLE
At some screen sizes, there is an extra "frame" around the wave area

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#298] opened 2019-01-05 01:27 UTC
At some screen sizes, there is an extra "frame" around the wave area

![image](https://user-images.githubusercontent.com/679486/50718577-60db7780-104e-11e9-8094-28961372656d.png)

**Comment by samreid** [comment] 2019-01-07 05:21
Oh, it's this:

```js
// Thin border to distinguish between the lattice node and the light screen.  This is not part of the
// waveAreaNode because that would extend its bounds
const borderNode = new Rectangle(
  0, 0, WaveInterferenceConstants.WAVE_AREA_WIDTH, WaveInterferenceConstants.WAVE_AREA_WIDTH, {
    stroke: 'white',
    lineWidth: 1,
    top: this.waveAreaNode.top - 0.5,
    centerX: this.waveAreaNode.centerX
  } );
```

**Comment by samreid** [comment] 2019-01-07 05:31
I improved the geometry for that part (keeping the same stroke) and can't seem to break it any more.  @arouinfar can you please review?

**Comment by arouinfar** [comment] 2019-01-07 18:59
This is not something I have noticed before, but was able to reproduce in dev.56. Looks like it's been fixed in master @samreid.

**Closed by arouinfar** 2019-01-07 18:59 UTC
Labels: status:ready-for-review
